spring.application.name=javaservice
server.port=8080

# H2 en memoria (se reinicia empty en cada arranque)
spring.datasource.url=jdbc:h2:mem:estudiantes;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Consola H2 disponible en http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
